---
version: "3"
services:
  mailgun-bouncebot:
    container_name: mailgun-bouncebot
    build: .
    environment:
      - API_KEY
      - CC
      - HOST
    ports:
      - ${PORT}:50708
    restart: unless-stopped
