---
version: "3"
services:
  mailgun-bouncebot:
    labels:
      traefik.port: 50708
      traefik.frontend.rule: "Host:mailhandler.grosinger.net"
      traefik.enable: true
      traefik.frontend.headers.SSLRedirect: true
    network_mode: default
    container_name: mailgun-bouncebot
    build: .
    volumes:
      - ./:/opt/app
    environment:
      - API_KEY
      - CC
      - HOST
    ports:
      - ${PORT}:50708
    restart: unless-stopped
